[package]
name = "andon-light-core"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
heapless = { version = "0.8.0", default-features = false }
log = "0.4.27"
