[package]
name = "andon-light-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[profile.dev]
incremental = false

[profile.release]
incremental = false

[dependencies]
quote = "^1.0"
syn = { version = "^2.0", features = ["derive", "parsing"] }
